RMS/Models/AssessmentViewModel.cs
using RMS.Common.BusinessEntities.Training;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace RMS.Models
{
    public class AssessmentViewModel 
    {
        public AssessmentPaperViewModel AssessmentPaper { get; set; }
        public List<AssementPaperDetailsViewModel> AssessmentPaperDetails { get; set; }
        public List<AssessmentQuestionsViewModel> AssessmentQuestions { get; set; }
        public IEnumerable<SelectListItem> ListCourses { get; set; }
    }


}

RMS/Models/AssignAssessmentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Models
{
    public class AssignAssessmentViewModel 
    {
        public int AssessmentPaperId { get; set; }
        public int CourseId { get; set; }
        public string  CourseName{ get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        //public List<AssementPaperDetailsViewModel> AssessmentPaperDetails { get; set; }
        public IEnumerable<SelectListItem> ListCourses { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime AssessmentDate { get; set; }

        [Required(ErrorMessage = " ")]
        [Range(0, 999, ErrorMessage = "Time duration can not exceed beyond 999.")]

        public int TimeDuration { get; set; }
        public DataTable dtEmp { get; set; }
    }

    public class EmployeeList
    {
        public string EmpName { get; set; }
        public int EmpId { get; set; }
    }
}

RMS/Models/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RMS.Models
{
    public class Result
    {
        public int Id { get; set; }
        public bool Status { get; set; }
    }
}

RMS/Controllers/AssessmentController.cs
using Domain.Entities;
using RMS.Common;
using RMS.Common.BusinessEntities.Training;
using RMS.Common.Constants;
using RMS.Helpers;
using RMS.Models;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Controllers
{
    [CheckAccess]
    public class AssessmentController :  ErrorController
    {

        private readonly ITrainingService _ITrainingService;
        private readonly IAssessmentService _IAssessmentService;

        /// <summary>
        /// Constructor for creating reference for Training service layer
        /// </summary>
        public AssessmentController(ITrainingService trainingService, IAssessmentService _assessmentService)
        {
            _ITrainingService = trainingService;
            _IAssessmentService = _assessmentService;
        }

        #region Action Methods
        public ActionResult CreateAssessment(string pcourseId)
        {
            int courseId = Convert.ToInt32(CheckAccessAttribute.Decode(pcourseId));
            AssessmentViewModel assessmentViewModel = GetAssessmentPaperByCourseId(courseId);
            return View("CreateAssessment", assessmentViewModel);

            //AssessmentPaperViewModel assessmentPaperViewModel = new AssessmentPaperViewModel();
            //assessmentPaperViewModel.TrainingCourses = LoadTrainingCourses();
            //return View("CreateAssessment", assessmentPaperViewModel);
        }

        [HttpPost]
        public ActionResult CreateAssessment(AssessmentViewModel assessmentPaperViewModel) //AssessmentPaperViewModel  assessmentPaperViewModel
        {
            int assessmentPaperId = 0;
            AssessmentPaperModel assessmentPaperModel = new AssessmentPaperModel();
            assessmentPaperModel.AssessmentPaperId = assessmentPaperViewModel.AssessmentPaper.AssessmentPaperId;
            assessmentPaperModel.CourseId = assessmentPaperViewModel.AssessmentPaper.CourseId;
            assessmentPaperModel.AssessmentDate = assessmentPaperViewModel.AssessmentPaper.AssessmentDate;
            assessmentPaperModel.TimeDuration = assessmentPaperViewModel.AssessmentPaper.TimeDuration;
            assessmentPaperModel.IsActive = true;
            assessmentPaperModel.CreatedOn = DateTime.Now;
            assessmentPaperModel.LastEditedOn = DateTime.Now;
            assessmentPaperId = _IAssessmentService.SaveAssessmentPaper(assessmentPaperModel);
            if (assessmentPaperId > 0)
            {
                string passessmentPaperId = CheckAccessAttribute.Encode(Convert.ToString(assessmentPaperId));
                return RedirectToAction("ShowAssessmentPaperDetails", new { Id = passessmentPaperId });
            }
            else
            {
                return View("Error");
            }
        }


        public ActionResult ShowAssessmentPaperDetails(string  id)
        {
            int assessmentPaperId = Convert.ToInt32(CheckAccessAttribute.Decode(id));
            AssessmentViewModel assessmentViewModel = GetAssessmentPaperById(assessmentPaperId);
            return View("ShowAssessmentPaperDetails", assessmentViewModel);
        }

        public ActionResult StartAssessment()
        {
            //AssessmentResultViewModel assessmentResultViewModel = new AssessmentResultViewModel();            
            //assessmentResultViewModel.TotalScore= 2;
            //assessmentResultViewModel.OutofScore = 3;
            //assessmentResultViewModel.Message = "dsdsdsdsdsd";
            //return View("Result", assessmentResultViewModel);
            AssessmentViewModel ObjSetAssessmentViewModel = new AssessmentViewModel();
            ObjSetAssessmentViewModel.ListCourses = LoadTrainingCourses("StartAssessment", Convert.ToInt32(Session["EmpID"]));
            return View("PaperDetails", ObjSetAssessmentViewModel);

        }
        public ActionResult GiveAssessment(int id)//public ActionResult Details(int id, int empId)
        {
            AssessmentViewModel assessmentViewModel = GetAssessmentPaperByCourseId(id);
            ViewData["EmployeeId"] = Convert.ToInt32(Session["EmpID"]);
            ViewData["PaperPrefix"] = "AssessmentViewModel.AssessmentPaper";
            ViewData["prefix"] = "AssessmentViewModel.AssessmentQuestions";
            return PartialView("_StartAssessment", assessmentViewModel);
        }       

        //public ActionResult GiveAssessment(int id, int empId)//public ActionResult Details(int id, int empId)
        //{

        //    AssessmentViewModel assessmentViewModel = GetAssessmentPaperById(id);
        //    ViewData["EmployeeId"] = empId;
        //    ViewData["PaperPrefix"] = "AssessmentViewModel.AssessmentPaper";
        //    ViewData["prefix"] = "AssessmentViewModel.AssessmentQuestions";
        //    return View("PaperDetails", assessmentViewModel);
        //}
        [HttpPost]
        public ActionResult Result(AssessmentViewModel assessmentViewModel, FormCollection objf)//(int empId, AssessmentViewModel assessmentViewModel)
        {
            AssessmentResultViewModel assessmentResultViewModel = new AssessmentResultViewModel();
            //assessmentResultViewModel.AssessmentPaperId = assessmentViewModel.AssessmentPaper.AssessmentPaperId;
            assessmentResultViewModel.AssessmentPaperId = Convert.ToInt32( objf["AssessmentViewModel.AssessmentQuestions[1].AssessmentPaperId"]);
            assessmentResultViewModel.AssessmentPaperId = Convert.ToInt32(objf["HfldAssessmentPaperId"]);
            
            assessmentResultViewModel.AssessmentDate = DateTime.Now;
            assessmentResultViewModel.EmployeeId = Convert.ToInt32(Session["EmpID"]);
            AssessmentResult assessmentResult = ConvertAssessmentResultViewModelToDomain(assessmentResultViewModel);
            DataTable dtResultDetails;
            dtResultDetails = new DataTable("AssessmentResultDetails");
            dtResultDetails.Columns.Add("AssessmentResultId", typeof(int));
            dtResultDetails.Columns.Add("QuestionId", typeof(int));
            dtResultDetails.Columns.Add("SelectedAnswer", typeof(string));
            dtResultDetails.Columns.Add("AnswerScore", typeof(int));
            dtResultDetails.Columns.Add("isactive", typeof(bool));
            dtResultDetails.Columns.Add("CreatedBy", typeof(int));
            dtResultDetails.Columns.Add("CreatedOn", typeof(DateTime));
            dtResultDetails.Columns.Add("LastEditedBy", typeof(int));
            dtResultDetails.Columns.Add("LastEditedOn", typeof(DateTime));

            //AssessmentViewModel 
            assessmentViewModel = GetAssessmentPaperById(assessmentResultViewModel.AssessmentPaperId);
            if (assessmentViewModel.AssessmentQuestions != null && assessmentViewModel.AssessmentQuestions.Count > 0)
            {
                foreach (var question in assessmentViewModel.AssessmentQuestions)
                {
                    string selectedAnswer = string.Empty;

                    if (question.IsMultiChoiceAnswer)
                    {

                        if(Convert.ToString (objf["Chk_AssessmentViewModel.AssessmentQuestions[" + question.QuestionId + "].Option1"]).Contains("true"))
                            selectedAnswer = selectedAnswer + " Option 1 ,";
                        if (Convert.ToString(objf["Chk_AssessmentViewModel.AssessmentQuestions[" + question.QuestionId + "].Option2"]).Contains("true"))
                            selectedAnswer = selectedAnswer + " Option 2 ,";
                        
                        if (!string.IsNullOrEmpty(question.Option3Description))
                        {
                            if (Convert.ToString(objf["Chk_AssessmentViewModel.AssessmentQuestions[" + question.QuestionId + "].Option3"]).Contains("true"))
                                selectedAnswer = selectedAnswer + " Option 3 ,";
                        }
                        
                        if (!string.IsNullOrEmpty(question.Option4Description))
                        {
                            if (Convert.ToString(objf["Chk_AssessmentViewModel.AssessmentQuestions[" + question.QuestionId + "].Option4"]).Contains("true"))
                                selectedAnswer = selectedAnswer + " Option 4 ,";
                        }

                        if (!string.IsNullOrEmpty(question.Option5Description))
                        {
                            if (Convert.ToString(objf["Chk_AssessmentViewModel.AssessmentQuestions[" + question.QuestionId + "].Option5"]).Contains("true"))
                                selectedAnswer = selectedAnswer + " Option 5 ,";
                        }
                        if (!string.IsNullOrEmpty(question.Option6Description))
                        {
                            if (Convert.ToString(objf["Chk_AssessmentViewModel.AssessmentQuestions[" + question.QuestionId + "].Option6"]).Contains("true"))
                                selectedAnswer = selectedAnswer + " Option 6 ,";
                        }
                    }
                    else
                    {
                        try
                        {
                            if (!string.IsNullOrEmpty(objf["Rbtn_AssessmentViewModel.AssessmentQuestions[" + question.QuestionId + "].Option"]))
                                selectedAnswer = objf["Rbtn_AssessmentViewModel.AssessmentQuestions[" + question.QuestionId + "].Option"];
                            
                        }
                        catch (Exception)
                        { }
                    }

                    selectedAnswer = selectedAnswer.TrimEnd(',');
                    if (selectedAnswer != "")
                    {
                        question.SelectedAnswer = selectedAnswer;
                        int score = 0;

RMS/Views/Assessment/AddNewQuestion.cshtml
@model RMS.Models.AssessmentViewModel
@{
    ViewBag.Title = "Add New Question";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="training-title margin-b-10">
        Add Assessment Question
               <img src="~/Content/css/Images/down-arrow.png" alt="down" />
            </div>
</div>

        @using (Html.BeginForm("AddNewQuestion", "Assessment", new { id = Model.AssessmentPaper.AssessmentPaperId }, FormMethod.Post, new { encType = "multipart/form-data", @class = "form-horizontal", id = "frmAssessmentDetails" }))
        {
            @Html.AntiForgeryToken()     
            @Html.HiddenFor(model => model.AssessmentPaper.AssessmentPaperId)      
            
            <div  class="col-md-12" id="divCourse">
                    <div class="panel-group">
                        <div class="panel panel-default" id="pnlAssessmentPaperDetails">
                            <div class="panel-heading">Assessment Paper Details</div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="col-md-2">@Html.LabelFor(model => model.AssessmentPaper.CourseId, "Course")</div>
                                            <div class="col-md-3">
                                                @Html.DisplayFor(model => model.AssessmentPaper.CourseName)
                                                @Html.HiddenFor(model => model.AssessmentPaper.CourseId)  
                                                @Html.HiddenFor(model => model.AssessmentPaper.CourseName)  
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="col-md-2">@Html.LabelFor(model => model.AssessmentPaper.AssessmentDate, "Assessment Date")</div>
                                            <div class="col-md-3">
                                                @Html.DisplayFor(model => model.AssessmentPaper.AssessmentDate, "{0:dd/MM/yyyy}")
                                                @Html.HiddenFor(model => model.AssessmentPaper.AssessmentDate)  
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="col-md-2">@Html.LabelFor(model => model.AssessmentPaper.TimeDuration, "Time Duration")</div>
                                            <div class="col-md-3">
                                                @Html.DisplayFor(model => model.AssessmentPaper.TimeDuration) Minutes
                                                @Html.HiddenFor(model => model.AssessmentPaper.TimeDuration)  
                                            </div>

                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="panel-group">
                        <div class="panel panel-default" id="pnlAssessmentQuestion">
                            <div class="panel-heading">Assessment Question</div>
                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-md-12">
                                        <span id="message">
                                            @{
            var msg = Convert.ToString(TempData["Result"]);
            if (!string.IsNullOrWhiteSpace(msg))
            {
                                                @msg
                                                <br />
                                                <script>
                                                    $("#message").addClass("MessageStyleSuccess");
                                                </script>
            }
                                            }
                                        </span>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        @Html.Partial("_AddQuestion", Model.AssessmentQuestions, new ViewDataDictionary(ViewData.Model.AssessmentQuestions) { { "prefix", "AssessmentQuestions" } })
                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-2">
                                    <input id="btnSave" type="submit" value="Save" class="buttonstyle" />&nbsp;
                                    <input id="btnCancel" type="button" value="Cancel" class="buttonstyle" />
                                </div>
                            </div>
                        </div>
                    </div>                
            </div> 
        }
    
<script type="text/javascript">
    $(document).ready(function () {
        $("#Option5").hide();
        $("#Option6").hide();

        $("#btnCancel").click(function () {
            window.location.href = '@Url.Action("ShowAssessmentPaperDetails", "Assessment", new { id = RMS.Helpers.CheckAccessAttribute.Encode(Convert.ToString(Model.AssessmentPaper.AssessmentPaperId )) })';
        });

        $('.required').change(function () {
            clearvalidation(this);
        });


        //$('input[type=file]').change(function () {
        //    // select the form and submit
        //    debugger;
        //    $('form').submit();
        //});


        $("#frmAssessmentDetails").submit(function (e) {
            var flag = Validation();
            var isAnswerSelected = true;
            if ($("input[type=checkbox]:checked").length === 0) {
                isAnswerSelected = false;
            }
            else if ($("input[type=checkbox]:checked").length >1) {
                $(".jq_MuliChoiceAnswer").val(true);
            }
            if (flag == false && isAnswerSelected== false) {
                $("#message").html("Please fill mandatory details.<br/>Please select correct answer for the question.");
                $("#message").addClass("MessageStyleFail");
                $(".requiredHiglight").first().focus();
                e.preventDefault();
            }
            else if (isAnswerSelected == false) {
                $("#message").html("Please select correct answer for the question.");
                $("#message").addClass("MessageStyleFail");
                $(".jq_AnsweOption").first().focus();
                e.preventDefault();
            }
            
        });
        $("#btnAddMoreOption").click(function (e) {
            if ($("#Option5").is(':visible') == false) {
                $("#Option5").show();
                $("#Option6").hide();
            }
            else {
                $("#Option6").show();
                $("#AddMoreOption").hide();
            }
        });
    });

    
</script>

RMS/Views/Assessment/CreateAssessment.cshtml
@*@model RMS.Models.AssessmentPaperViewModel*@
@model RMS.Models.AssessmentViewModel

@{
    ViewBag.Title = "Create Assessment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-md-12">
    <div class="training-title margin-b-10">
        Create Assessment
               <img src="~/Content/css/Images/down-arrow.png" alt="down" />
    </div>
</div>


@using (Html.BeginForm("CreateAssessment", "Assessment", FormMethod.Post, new { encType = "multipart/form-data", @class = "form-horizontal", @id = "frmCreateAssessment" }))
        {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="col-md-12">
        <span id="message">
            @{
            var msg = Convert.ToString(TempData["Result"]);
            if (!string.IsNullOrWhiteSpace(msg))
            {
                @msg
                <br />
                <script>
                                    $("#message").addClass("MessageStyleSuccess");
                </script>
            }
            }
        </span>
    </div>

    <div class="col-md-12">
        <div class="panel panel-default" id="pnlTrainingCourse">
            <div class="panel-heading">Create Assessment</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="editor-label">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.AssessmentPaper.CourseId, "Course")<label style="color: red; padding-left: 2px;">*</label>
                                </div>
                            </div>
                            <div class="editor-field">
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.AssessmentPaper.CourseName)
                                    @Html.HiddenFor(model => model.AssessmentPaper.CourseId)
                                </div>
                            </div>

                        </div>
                    </div>
                </div>



                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="editor-label">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.AssessmentPaper.TimeDuration, "Time Duration")<label style="color: red; padding-left: 2px;">*</label>
                                </div>
                            </div>
                            <div class="editor-field">
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.AssessmentPaper.TimeDuration, new {  @class = "textstyle required" }) Minutes
                                    @Html.ValidationMessageFor(model => model.AssessmentPaper.TimeDuration, "", new { @style = "color:red;" })

                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="editor-label">
                                <div class="col-md-2">
                                    @Html.LabelFor(model => model.AssessmentPaper.AssessmentDate, "Assessment Date")<label style="color: red; padding-left: 2px;">*</label>
                                </div>
                            </div>
                            <div class="editor-field">
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.AssessmentPaper.AssessmentDate, "{0:dd/MM/yyyy}", new { @class = "datepicker required", @readonly = "readonly" })

                                </div>
                            </div>


                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">

                            <div class="col-md-2"></div>
                            <div class="col-md-8">
                                @if (Model.AssessmentPaper.AssessmentPaperId != 0)
                                {
                                    <input id="btnQuestion" type="submit" value="Update & View Question" class="buttonstyle" />
                                }else
                                {
                                    <input id="btnSave" type="submit" value="Submit Assessment & View Question" class="buttonstyle" />
                                }
                                &nbsp;<input id="btnCancel" type="reset" value="Reset" class="buttonstyle" />
                            </div>
                            <div class="col-md-2">
                            </div>

                        </div>
                        <div class="col-md-12">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 
            
            
        }

<script src="~/Content/Scripts/jquery-ui-1.8.20.js"></script>
<link href="~/Content/css/jquery-ui.css" rel="stylesheet" />

<script type="text/javascript">
    $(document).ready(function () {
        if ($('#AssessmentPaper_AssessmentDate').val() == "01/01/1900" || $('#AssessmentPaper_AssessmentDate').val() == "01/01/1900 00:00:00"
            || $('#AssessmentPaper_AssessmentDate').val() == "01/01/0001" || $('#AssessmentPaper_AssessmentDate').val() == "01/01/0001 00:00:00")
        {
            $('#AssessmentPaper_AssessmentDate').val('');
        }


        $.validator.addMethod('date',
           function (value, element) {
               if (this.optional(element)) {
                   return true;
               }
               var valid = true;
               try {
                   $.datepicker.parseDate('dd/mm/yy', value);
               }
               catch (err) {
                   valid = false;
               }
               return valid;
           });

        $('#AssessmentPaper_AssessmentDate').datepicker(
             {
                 dateFormat: "dd/mm/yy",
                 autoclose: true,
                 minDate: 0
             }).val();

        $("#btnCancel").click(function (e) {
            $("#frmCreateAssessment")[0].reset();
            $("#frmCreateAssessment").find("[data-valmsg-replace]")
            .removeClass("field-validation-error")
            .addClass("field-validation-valid")
            .empty();
            $('#AssessmentPaper_AssessmentDate').datepicker().val('');
            ClearBorderColor();
            $("#message").html("");
            e.preventDefault();
        });

        $('.required').change(function () {
            clearvalidation(this);
        });

        $("#frmCreateAssessment").submit(function (e) {
            var flag = Validation();
            if (flag == false) {
                $("#message").html("Please fill mandatory details.");
                $("#message").addClass("MessageStyleFail");
                $(".requiredHiglight").first().focus();
                e.preventDefault();
            }
            
        });
    });

</script>

RMS/Views/Assessment/Result.cshtml
@model RMS.Models.AssessmentResultViewModel

@{
    ViewBag.Title = "Result";
}


<div class="col-md-12">
    <div class="training-title margin-b-10">
        Assessment Paper Result
               <img src="~/Content/css/Images/down-arrow.png" alt="down" />
    </div>
</div>

<div class="col-md-12">
   
        <div class="panel-group">
            <div class="panel panel-default" id="pnlTrainingCourse">
                <div class="panel-heading">Assessment Paper Result Details</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12" >
                            @if (Model.Message =="1")
                            {
                           <div class="MessageStyleSuccess">You have scored @Model.TotalScore.ToString() out of @Model.OutofScore.ToString() in this assessment.</div>
                            }
                            else
                            {
                                <div class="MessageStyleSuccess">You already submited your assessment.</div> 
                            }                               
                        </div>
                        <div class="col-md-12" style="text-align :center">
                            <a href="javascript:window.opener='x';window.close();"><input id="btnCancel" type="button" value="Close" class="buttonstyle"  /></a>
                        </div> 
                    </div>                   
                </div>                   
                </div>
            </div>
        </div>


    