RMS/Controllers/VendorMasterController.cs
using Domain.Entities;
using RMS.Common.Constants;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
 
namespace RMS.Controllers
{
    public class VendorMasterController : ErrorController
    {
        //
        // GET: /VendorMaster/
        private readonly ITrainingService _service;

        public VendorMasterController(ITrainingService service)
        {
            _service = service;
        }

        public ActionResult VendorDetails()
        {
            List<VendorModel> lstVendorModel = new List<VendorModel>();

            DataSet dsVendor = _service.GetTrainingVendorDetails();
            for (int i = 0; i < dsVendor.Tables[0].Rows.Count; i++)
            {
                VendorModel objVendorModel = new VendorModel();
                objVendorModel.VendorId = Convert.ToInt32(dsVendor.Tables[0].Rows[i]["VendorID"]);
                objVendorModel.VendorName = dsVendor.Tables[0].Rows[i]["VendorName"].ToString();
                objVendorModel.VendorEmailId = dsVendor.Tables[0].Rows[i]["VendorEmail"].ToString();
                objVendorModel.ContactPersonName = dsVendor.Tables[0].Rows[i]["ContactPerson"].ToString();
                objVendorModel.ContactPersonNumber = dsVendor.Tables[0].Rows[i]["ContactPersonNumber"].ToString();
                objVendorModel.Expertise = dsVendor.Tables[0].Rows[i]["Expertise"].ToString();

                lstVendorModel.Add(objVendorModel);
            }

            return View(lstVendorModel);
        }

        [HttpGet]
        public ActionResult EditVendorDetails(int VendorId)
        {
            if (VendorId != 0)
            {

                VendorModel objVendorModel = new VendorModel();
                DataSet dsVendorDetails = _service.GetVendorDetailsByVendorId(VendorId);

                objVendorModel.VendorId = VendorId;
                objVendorModel.VendorName = dsVendorDetails.Tables[0].Rows[0]["VendorName"].ToString();
                objVendorModel.VendorEmailId = dsVendorDetails.Tables[0].Rows[0]["VendorEmail"].ToString();
                objVendorModel.ContactPersonName = dsVendorDetails.Tables[0].Rows[0]["ContactPerson"].ToString();
                objVendorModel.ContactPersonNumber = dsVendorDetails.Tables[0].Rows[0]["ContactPersonNumber"].ToString();
                objVendorModel.Expertise = dsVendorDetails.Tables[0].Rows[0]["Expertise"].ToString();

                return View(objVendorModel);
            }
            else
            {
                return View();
            }

        }
        [HttpPost]
        public ActionResult SaveVendorDetails(VendorModel objVendorModel, string Command)
        {
            

            if (ModelState.IsValid)
            {
                if (Command == "Save")
                {
                    
                    int status = 0;
                    if (objVendorModel.VendorId != 0)
                    {
                        status = _service.UpdateVendorDetails(objVendorModel);
                    }
                    else
                    {
                        status = _service.SaveVendorDetails(objVendorModel);
                    }

                    if (status == 1)
                    {
                        TempData["Result"] = "Vendor details saved successfully";
                    }
                }
                else if (Command == "Cancel")
                {
                    return RedirectToAction("VendorDetails");
                }
                return RedirectToAction("VendorDetails");
            }
            else
            {
                TempData[CommonConstants.Message] = "Contact Person Number should be number with comma seperated field";
                return RedirectToAction("EditVendorDetails");
            }
        }


        [HttpPost]
        public JsonResult doesEmailExists(VendorModel objVendorModel)
        {
            //string duplicateState = string.Empty;
            var duplicateState = _service.GetDuplicateStatusOfEmialId(objVendorModel.VendorEmailId);
            return Json(duplicateState == "0");
        }


        public ActionResult DeleteVendorDetails(int VendorId)
        {
            int deleteStatus = _service.DeleteVendorDetails(VendorId);
            if (deleteStatus == -1)
            {
                TempData["Result"] = "Vendor cannot be deleted";
            }
            else
            {
                TempData["Result"] = "Vendor deleted successfully";
            }

            return RedirectToAction("VendorDetails");
        }

    }
}

RMS/Views/VendorMaster/EditVendorDetails.cshtml
@model Domain.Entities.VendorModel
@{
    ViewBag.Title = "EditVendorDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SaveVendorDetails", "VendorMaster", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <fieldset>
            <legend></legend>
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">Vendor Details</div>
                    <div class="panel-body">
                        <div class="container">
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <span id="message">
                                            @{
        var msg = Convert.ToString(TempData["Result"]);
        if (!string.IsNullOrWhiteSpace(msg))
        {
                                                @msg
                                                <br />
                                                <script>
                                                    $("#message").addClass("MessageStyleSuccess");
                                                </script>
        }
                                            }
                                        </span>
                                        <br />
                                        @Html.ValidationMessageFor(model => model.ContactPersonNumber, string.Empty, new { @class = "MessageStyleFail"})
                                        @Html.ValidationMessageFor(model => model.VendorEmailId, string.Empty, new { @class = "MessageStyleFail"})
                                    </div>
                                </div>
                                </div>
                            <div class="row">
                                <div class="form-group">
                                    @Html.HiddenFor(model=>model.VendorId)
                                    <div class="col-md-2"><label class="Labelstyle">Vendor Name : </label><span style="color: Red;" id="spanVendorName">*</span></div>
                                    <div class="col-md-3">@Html.TextBoxFor(model => model.VendorName, new { @class = "textstyle required" })</div>
                                    <div class="col-md-2"><label class="Labelstyle">Vendor EmailID : </label><span style="color: Red;" id="spanVendorEmailID">*</span></div>
                                    <div class="col-md-3">@Html.TextBoxFor(model => model.VendorEmailId, new { @class = "textstyle required" })</div>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-2"><label class="Labelstyle">Contact Person Name : </label><span style="color: Red;" id="spanContactPersonName">*</span></div>
                                    <div class="col-md-3">@Html.TextBoxFor(model => model.ContactPersonName, new { @class = "textstyle required" })</div>
                                    <div class="col-md-2"><label class="Labelstyle">Contact Person Number : </label><span style="color: Red;" id="spanContactPersonNumber">*</span></div>
                                    <div class="col-md-3">@Html.TextBoxFor(model => model.ContactPersonNumber, new { @class = "textstyle required", msg="Contact Person Number accepts only numbers and comma" })
                                        
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-2"><label class="Labelstyle">Expertise : </label><span style="color: Red;" id="spanExpertise">*</span></div>
                                    <div class="col-md-3">@Html.TextAreaFor(model => model.Expertise, new { @class = "textareastyle required" })</div>
                                    <div class="col-md-2"><input type="submit" id="btnSave" value="Save" name="Command" /><input type="button" id="btnCancel" value ="Cancel" name="Command"/></div>
                                </div>
                            </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
}

<script type="text/ecmascript">

    $(document).ready(function () {
        $(function () {
            if ($('#VendorId').val() != 0) {
                $('#VendorName').attr("disabled", "disabled");
            }
            else {
                $('#VendorName').removeAttr("disabled");
            }

            $("#btnCancel").attr("onClick", "document.location.href='@Html.Raw(Url.Action("VendorDetails", "VendorMaster"))'");

            $("form").submit(function (e) {
                var flag = SaveClickValidation();
                if (flag == false) {
                    $("#message").html("Please fill mandatory details.");
                    $("#message").addClass("MessageStyleFail");
                    e.preventDefault();
                }

            });
        });
    });

    function SaveClickValidation() {

        Validation();
    }
                
</script>

RMS/Views/VendorMaster/VendorDetails.cshtml
@model IList<Domain.Entities.VendorModel>
@{
    ViewBag.Title = "VendorDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="container">
    
        <fieldset>
            <legend></legend>
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">Vendor Details Form</div>
                    <div class="panel-body">
                        <div class="container">
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <span id="message">
                                            @{
                                                var msg = Convert.ToString(TempData["Result"]);
                                                if (!string.IsNullOrWhiteSpace(msg))
                                                {
                                                @msg
                                                <br />
                                                <script>
                                                    $("#message").addClass("MessageStyleSuccess");
                                                </script>
                                                }
                                            }
                                        </span>
                                    </div>
                                </div>
                                </div>
                           
                            <div class="row">
                                <div class="form-group">
                                    <a href="@Url.Action("EditVendorDetails", "VendorMaster", new { @VendorId = 0 })">Add New Vendor </a>
                                </div>
                            </div>
                           <div id="divGrid">
                               <div class ="container">
                            
                                <table id="viewreport" class="table table-striped" style="border: thin;">
                                <thead>
                                    <tr>
                                        @*<th>VendorID</th>*@
                                        <th>VendorName</th>
                                        <th>VendorEmailId</th>
                                        <th>ContactPerson</th>
                                        <th>ContactPersonNumber</th>
                                        <th>Expertise</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody id="tblBody">
                                    @if (Model.Count > 0)
                                    {
                                        foreach (var vendor in Model)
                                        {                     
                                        <tr>
                                            @*<td hidden>@vendor.VendorId</td>*@
                                            <td>@vendor.VendorName</td>
                                            <td>@vendor.VendorEmailId</td>
                                            <td>@vendor.ContactPersonName</td>
                                            <td>@vendor.ContactPersonNumber</td>
                                            <td>@vendor.Expertise</td>
                                            <td data-id="@vendor.VendorId" class="edit" style="text-align:center;" ><a href="@Url.Action("EditVendorDetails", "VendorMaster", new { @VendorId = @vendor.VendorId })">
                                            <img src="@Url.Content("~/Content/css/Images/Edit.gif")" alt="Edit" title="Edit" width="20"/></a></td>

                                            <td data-id="@vendor.VendorId" class="delete" style="text-align:center;"><a href="@Url.Action("DeleteVendorDetails", "VendorMaster", new { @VendorId = @vendor.VendorId })">
                                            <img  src="@Url.Content("~/Content/css/Images/Delete.gif")" alt="Delete" title="Delete" width="20"/></a></td>

                                        </tr>
                                        }
                                    }
                                </tbody>
                                </table>
                            
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
        </fieldset>

</div>
<script type="text/ecmascript">
    $(document).ready(function () {
        var totalRecord = '@Model.Count';
        hidewaiting();
        if (totalRecord > 0) {
            $('#viewreport').dataTable();
        }
    });
</script>