RMS/Models/FileHelperViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RMS.Common.BusinessEntities.Common;

namespace RMS.Models
{
    public class FileHelperViewModel
    {
        public FileHelperViewModel() 
        {
            this.FileDetails = new List<FileDetail>();
        }

        public FileHelperViewModel(List<FileDetail> fileDetails)
        {
            this.FileDetails = fileDetails;
        }

        public List<FileDetail> FileDetails { get; set; }
    }
}

RMS/Models/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RMS.Models
{
    public class Result
    {
        public int Id { get; set; }
        public bool Status { get; set; }
    }
}

RMS/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using Domain.Entities;
using Services.Interfaces;
using Services;
using System.Configuration;
using RMS.Common.Constants;
using RMS.Common;
using RMS.Helpers;
using Infrastructure;
using System.IO;
using System.Text;
using RMS.Common.BusinessEntities.Menu;

namespace RMS.Controllers
{
    public class CommonController : ErrorController
    {
        //private List<CommonModel> ListEmployeeListModel = new List<CommonModel>();
        //private CommonModel objCommonModel = new CommonModel();

        private readonly ICommonService _CommonService;

        public CommonController(ICommonService service)
        {
            _CommonService = service;
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public string Index(List<Domain.Entities.CommonModel> model)
        {
            string pEmpID = string.Empty;
            string pEmpName = string.Empty;

            foreach (CommonModel revInfo in model)
            {
                if (revInfo.Checked == true)
                {
                    pEmpID +=  "," + revInfo.EmpID ;
                    pEmpName += ", " +revInfo.FirstName + " " + revInfo.LastName ;
                }
            }

            return pEmpID.Remove(0, 1) + "~" + pEmpName.Remove(0, 2);
        }

        [HttpGet]
        public FileResult DownloadFile(string filePath, string fileName)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(@Server.MapPath(filePath));
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        //[HttpGet]
        [OutputCache(Duration = 86400, VaryByParam = "none")]
        public ActionResult EmployeeList()
        {
            return PartialView("EmployeeList", CommonRepository.FillPopUpEmployeeList(""));
        }
   

        [HttpGet]
        public ActionResult DeleteFile(string fileId,string filePath, string fileName, string physicalFile, string module , string entityId, string targetId, string dir)
        {
            FileUploadModel objFileUploadModel = new FileUploadModel();
            
            if (module == "CourseContent")
            {
                return RedirectToAction("UpdateFileDetail", "TrainingCourse", new { module = module, entityId = entityId, fileName = physicalFile, fullFile = filePath, targetId = targetId, dir = dir });
            }
            else if (module == "CourseDAR")
            {
                return RedirectToAction("UpdateFileDetail", "TrainingCourse", new { module = module, entityId = entityId, fileName = physicalFile, fullFile = filePath, targetId = targetId, dir = dir });
            }
            else if (module == "CourseTrainer")
            {
                return RedirectToAction("UpdateFileDetail", "TrainingCourse", new { module = module, entityId = entityId, fileName = physicalFile, fullFile = filePath, targetId = targetId, dir = dir });
            }
            else if (module == "CourseInvoice")
            {
                return RedirectToAction("UpdateInvoiceDetail", "TrainingCourse", new { fileId = fileId, module = module, entityId = entityId, fileName = physicalFile, fullFile = filePath, targetId = targetId, dir = dir });
            }
            return PartialView(CommonConstants.FileHelperView, objFileUploadModel);
        }

        [CheckAccess]        
        [ChildActionOnly]
        public ActionResult GetMenu()
        {
            List<Menu> MenuList = _CommonService.GetAuthoriseMenuList(Convert.ToInt32( Session["EmpID"]));
            HttpContext context = System.Web.HttpContext.Current;            
            bool IsAuthoriseUser = MenuList.Exists(m => string.Concat(m.baseUrl, m.PageURL, Convert.ToString(context.Request.Url.Query)).Equals(Convert.ToString(context.Request.Url.OriginalString), StringComparison.InvariantCultureIgnoreCase));
            return PartialView("_menu", MenuList);           
        }

        public ActionResult Home()
        {
            return View("home");
        }

    }
}

RMS/Views/Shared/EmployeeList.cshtml
@model List<Domain.Entities.CommonModel>

@using RMS.Common.Constants;
@{    
    Layout = "";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EmployeeList</title>
</head>
<body>
    @*@using (Html.BeginForm("Index", "Common", FormMethod.Post, new { @model = Model, @id = "form1" }))
        { 
    *@
    <div id="login-box">
        @using (Html.BeginForm("Index", "Common", FormMethod.Post, new { @model = Model, @id = "form1" }))
        {    
            
            <table>
                <tr>
                    <td colspan="4">
                        <input type="button" value="Select" id="BtnFirstSelect" class="buttonstyle" /></td>

                </tr>
            </table>
@*<div style="overflow-y: scroll">*@
            <table id="viewreport" class="table table-striped" style="border: thin;">
                <thead>
                    <tr>
                        <th>Select</th>
                        <th>EMPCode</th>
                        <th>Full Name</th>
                        <th>Designation</th>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <div id="test"></div>
                        </td>
                    </tr>
                </thead>
                <tbody id="tblBody">
                    @{
            int i = 0;
            foreach (var report in Model)
            {                           
                
                        <tr>
                            <td>@Html.CheckBox(Model[i].FirstName + ' ' + Model[i].LastName, Model[i].Checked, new {@class = Model[i].EmpID })</td>
                            <td>@Html.LabelFor(m => m[i].EMPCode, Model[i].EMPCode)</td>
                            <td>@Html.LabelFor(m => m[i].FirstName, Model[i].FirstName)  @Html.LabelFor(m => m[i].LastName, Model[i].LastName)</td>
                            <td>@Html.LabelFor(m => m[i].Designation, Model[i].Designation)
                                @Html.HiddenFor(m => m[i].EmpID, Model[i].EmpID)
                                @Html.HiddenFor(m => m[i].FirstName, Model[i].FirstName)
                                @Html.HiddenFor(m => m[i].LastName, Model[i].LastName)
                            </td>
                        </tr>
                i++;
            }
                    }
                </tbody>
            </table>
@*</div>*@
            <table>
                <tr>
                    <td colspan="4">
                        <input type="button" value="Select" id="BtnSecondSelect" class="buttonstyle" /></td>

                </tr>
            </table>
        }
    </div>
    @*}*@
</body>
</html>

<script>
    var table = $('#viewreport').dataTable();
</script>

RMS/Views/Shared/Home.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
</head>
<body>
    <div>
        Welcome ..............
    </div>
</body>
</html>

RMS/Views/Shared/RoleManagement.cshtml
@model RMS.Models.MasterViewModel
@using System.Data;

@{
    ViewBag.Title = "Role Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="form-horizontal">
    @*<div class="panel-group1">*@

    <div class="form-group">
        <div class="col-md-12">
            @{ Html.RenderAction("EmployeeList", "Common");}
        </div>
    </div>

    <div class="panel panel-default" id="pnlrolemgmt">
        <div class="panel-heading">Role Management</div>
        @using (Html.BeginForm("GetMasterRoles", "master", FormMethod.Post, new { @masterViewModel = Model,  @class = "form-horizontal" }))
        {
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">Role Name</div>
                    <div class="col-md-3">@Html.DropDownListFor(m => m.Roles, new SelectList(Model.Roles, "value", "text", Model.SelectedRole))
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">EmployeeName  : <span style="color: Red">*</span></div>
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.SelectedEmployeeName, new { @class = "TextAreastyle", @readonly = true })
                        @Html.HiddenFor(model => model.SelectedEmployeeID)
                        <a href="#login-box" class="login-window" id="check">
                            <img  src="@Url.Content("~/Content/css/Images/find.png")" alt="Find" title="Find"/>
                        </a>
                        @Html.ValidationMessageFor(m => m.SelectedEmployeeID)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <input type="submit" value="Submit" name="SubmitRoles" id="submitKss" class="buttonstyle" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<script src="~/Content/Scripts/jquery-ui-1.8.20.js"></script>
<link href="~/Content/css/jquery-ui.css" rel="stylesheet" />
<script type="text/javascript">

    $(document).ready(function () {
        hidewaiting();

        // Employee Popup   BtnSecondSelect
        $("#BtnFirstSelect,#BtnSecondSelect").click(function () {
            checkbox_id = '';
            checkbox_value = '';
            var rowcollection = table.$("input[type='checkbox']:checked", { "page": "all" });
            rowcollection.each(function (index, elem) {
                checkbox_value += ',' + $(elem).attr("name");
                checkbox_id += ',' + $(elem).attr("class");
            });
            checkbox_id = checkbox_id.replace(checkbox_id.charAt(checkbox_id.indexOf(",")), "");
            checkbox_value = checkbox_value.replace(checkbox_value.charAt(checkbox_value.indexOf(",")), "");

            $('#SelectedEmployeeID').val(checkbox_id);
            $("#SelectedEmployeeName").val(checkbox_value);
            $('#login-box').dialog('close');
        })

        $(function () {
            var dialog, form
            dialog = $("#login-box").dialog({
                autoOpen: false,
                height: 750,
                width: 1000,
                left: 500,
                modal: true,
                dialogClass: 'dlgfixed',
                //position: ['center', 'top'],
                //position: ({ my: 'center', of: 'center', collison: 'fit' }),
                close: function () {
                    //form[0].reset();
                    //allFields.removeClass("ui-state-error");
                }
            });

            form = dialog.find("form").on("submit", function (event) {

            });

            $("#check").bind("click", function () {
                dialog.dialog("open");
            });
        });

    });
</script>

RMS/Views/Shared/_FileHelperView.cshtml
@model Domain.Entities.FileUploadModel
@using RMS.Common.BusinessEntities.Common;

@{ if (Model.FileViewMode == 0)
   {
    <table class="table table-striped">
        <tr>
            <th style="width: 250px;">File Name</th>
            <th style="width: 150px;">Download File </th>
            @if (Model.DeleteFlag)
            {
                <th style="width: 150px;">Delete</th>    
            }
        </tr>

        @foreach (var item in Model.FileDetails)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td class="actionlink">
                    @Html.ActionLink("Download", "DownloadFile", "Common", new { filePath = item.FilePath, fileName = item.FileName }, new {/* id=item.PrimaryKey */ })
                </td>
                @if (Model.DeleteFlag)
                {
                    <td class="actionlink">
                        @Ajax.ActionLink("Delete", "DeleteFile", "Common", new { fileId = item.FileId, filePath = item.FilePath, fileName = item.FileName, physicalFile = item.PhysicalFileName, module = Model.Module, entityId = Model.EntityID, targetId = Model.TargetId, dir = Model.FileDirectory }, new AjaxOptions { UpdateTargetId = Model.TargetId, InsertionMode = InsertionMode.Replace, HttpMethod = "GET" })
                </td>
                }
            </tr>
        }

    </table>
   }
   else
   {
       
       
    <table>
        @foreach (var item in Model.FileDetails)
        {     
            if (!string.IsNullOrWhiteSpace(item.FileName))
            {
            @Html.ActionLink(item.FileName, "DownloadFile", "Common", new { filePath = item.FilePath, fileName = item.FileName }, new { @style = "color: Blue;text-decoration: underline;" }) 
            <span>&nbsp;</span><span>&nbsp;</span><span>&nbsp;</span>   
        }
        }

    </table>
   
   }
    
}

RMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title Training Module</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="bootstrapcss/bootstrap.min.css" rel="stylesheet">


    <meta name="viewport" content="width=device-width" />


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")




    <script src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    @Styles.Render("~/Content/css")


</head>
<body>
    <header>
        <div class="header-right-image img-responsive margin-b5">
            <div class="pull-left logo">
                <img src="~/Content/css/Images/Rave-logo.png" class="img-responsive">
            </div>
            <div class="pull-right rm">
                Resource Management
            </div>
        </div>
        <div class="header-strip margin-b-10">
        </div>
    </header>

    <div class="container">

        @*<div class="row">
            <div class="col-md-12">
                <p class="pull-right">
                    Welcome! <span class="UserNameStyle"><i>@{
                        string[] words = User.Identity.Name.ToString().Replace("RAVE-TECH.CO.IN\\", "").Split('.');
                        string a = words[0].Substring(0, 1).ToUpper() + words[0].Substring(1) + "." + words[1].Substring(0, 1).ToUpper() + words[1].Substring(1);
                        @a;
                    }
                    </i></span>
                </p>
            </div>
        </div>*@
        <div class="content-wrapper">
            @{
                Services.CommonService objservice = new Services.CommonService();
                List<RMS.Common.BusinessEntities.Menu.Menu> MenuList = objservice.GetAuthoriseMenuList(Convert.ToInt32(Session["EmpID"]));
                bool IsAuthoriseUser = MenuList.Exists(m => string.Concat(m.baseUrl, m.PageURL, Convert.ToString(HttpContext.Current.Request.Url.Query)).Equals(Convert.ToString(HttpContext.Current.Request.Url.OriginalString), StringComparison.InvariantCultureIgnoreCase));
                //if (!IsAuthoriseUser)
                //{
                //Response.Redirect(System.Configuration.ConfigurationManager.AppSettings[RMS.Common.Constants.CommonConstants.OldRMSBaseUrl]);
                //}
                //else {
                Html.RenderAction("GetMenu", "Common");
                        //}
            }

        </div>

        <div class="row">
            <div class="col-md-12" id="body">
                <div id="wait" class="wait">
                    <img src="@Url.Content("~/Content/css/Images/LoadingRed.gif")" alt="Wait" />
                </div>
                @RenderSection("featured", required: false)
                @*<section class="content-wrapper main-content clear-fix">*@
                <div class="row">
                    @RenderBody()
                </div>
                @*</section>*@
            </div>
        </div>
    </div>

    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                @*<p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>*@
            </div>
        </div>
    </footer>


</body>
</html>

<script type="text/javascript">
    //$(document).ready(function () {
    //    var username = $(".UserNameStyle").html();
    //    username = username.replace("RAVE-TECH.CO.IN", "");

    //    alert(username);
    //    $(".UserNameStyle").html() = username;

    //});

</script>

RMS/Views/Shared/_Menu.cshtml
@model IEnumerable<RMS.Common.BusinessEntities.Menu.Menu>

<link  href="@Url.Content("~/Content/css/menu.css")" type="text/css" rel="stylesheet" />

<div class="float-right menu-bg" id="divMenu">

    <ul >
        @{
            foreach (var menu in Model)
            {
                if (menu.ParentID == 0)
                {                              
                <li class="menu">@menu.PageName
                    @if (menu.SubMenu != null)
                    {
                        <ul>
                            @foreach (var submenu in menu.SubMenu)
                            {
                                if(submenu.PageName !="Start Assessment")
                                {
                                     <li><a href="@string.Concat(submenu.baseUrl, submenu.PageURL)">@submenu.PageName</a></li>
                            }
                                else
                                {
                                    <li><a href="@string.Concat(submenu.baseUrl, submenu.PageURL)" onclick="window.open(this.href, 'mywin','left=20,top=20,width=screen.width,toolbar=1,resizable=0'); return false;">@submenu.PageName</a></li>
                            }
                            }
                        </ul>
                    }
                </li>
                }
            }
        }
    </ul>
  

     @*<ul>
        @{
            foreach (var menu in Model)
            {
                if (menu.ParentID == 0)
                {                              
            <a href="@string.Concat(menu.baseUrl, menu.PageURL)" >
                <li>@menu.PageName
                    @if (menu.SubMenu != null)
                    {
                        <ul>
                            @foreach (var submenu in menu.SubMenu)
                            {
                                <a href="@string.Concat(submenu.baseUrl, submenu.PageURL)"><li>@submenu.PageName</li></a>
                            }
                        </ul>
                    }
                </li>
            </a>
                }
            }
        }
    </ul>*@
</div>

RMS/Views/Shared/_Result.cshtml
 @* Neelam : 25/07/2017 start. IssueId 59566*@
@{
    Layout = null;
}

 <div style="text-align: center;">
    
        @{
            var message = Convert.ToString(ViewData["Result"]);
            if (!string.IsNullOrWhiteSpace(message))
            {
            <span class="Messagetext" id="message" style="text-align:center">@message</span> <br />
            }
        }
     
        </div>
  @*Neelam : 25/07/2017 start. IssueId 59566*@